name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
  SCRIPT_RELEASE_FILE: edtmp_${{ github.ref_name }}.sh
  SCRIPT_RELEASE_PKG: edtmp_${{ github.ref_name }}_scripts.tar.gz

jobs:
  pack_scripts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Versioning
        run: |
          echo "Versioning"
          sed -i "s/{{VERSION}}/${{ github.ref_name }}/" edtmp.sh
          head -n 20 edtmp.sh

      - name: Pack
        run: |
          echo "Pack files"
          cp edtmp.sh ${{ env.SCRIPT_RELEASE_FILE }}
          tar -zcf ${{ env.SCRIPT_RELEASE_PKG }} ${{ env.SCRIPT_RELEASE_FILE }}

      - name: Archive packed files
        uses: actions/upload-artifact@v4 
        with:
          name: edtmp
          path: |
            ${{ env.SCRIPT_RELEASE_PKG }}
          if-no-files-found: error
          retention-days: 1

              
  pack_changelog:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive CHANGELOG
        uses: actions/upload-artifact@v4 
        with:
          name: changelog
          path: |
            CHANGELOG.md
          retention-days: 1

          
  release:
    needs: [pack_scripts, pack_changelog]
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact from pack_scripts job
        uses: actions/download-artifact@v4
        with: 
          name: edtmp

      - name: Download artifact from pack_changelog job
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ env.SCRIPT_RELEASE_PKG }}
        
